version: '3'

services:
  fritzinfluxdb:
    container_name: fritzinfluxdb
    image: bbricardo/fritzinfluxdb:latest
    restart: unless-stopped
    environment:
      # FritzBox configuration
      - FRITZBOX_USERNAME=fritzinflux
      # this var should be defined in an ".env" file
      - FRITZBOX_PASSWORD=XYZ

      # InfluxDB configuration
      - INFLUXDB_VERSION=2
      - INFLUXDB_HOSTNAME=influxdb-host-or-ip
      - INFLUXDB_ORGANISATION=YourOrg
      - INFLUXDB_BUCKET=fritzinfluxdb
      # this var should be defined in an ".env" file
      - INFLUXDB_TOKEN=MyWriteTokenToBucket-fritzinfluxdb

      # for more config options check fritzinfluxdb-sample.ini

    # enable to write debug information to docker logs
    # command:
    #   - "python"
    #   - "/app/fritzinfluxdb.py"
    #   - "-v"